# Generated by Django 4.2.1 on 2023-05-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0004_remove_customuser_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkout',
            name='abc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
