# Generated by Django 4.2.1 on 2023-05-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0005_userworkout_abc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userworkout',
            name='abc',
        ),
    ]
