# Generated by Django 4.2.1 on 2023-05-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0007_exercise_workoutexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='calories',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_weight',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='reps',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='sets',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
