# Generated by Django 4.2.1 on 2023-05-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0008_alter_exercise_calories_alter_goal_goal_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='is_standard',
            field=models.BooleanField(default=False),
        ),
    ]
