# Generated by Django 4.2.1 on 2023-05-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0009_workout_is_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
