# Generated by Django 4.2.1 on 2023-06-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0010_alter_workout_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='rest_time',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
