# Generated by Django 4.2.1 on 2023-06-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0012_alter_workoutexercise_rest_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='goal_weight',
            new_name='goal_calories',
        ),
    ]
