# Generated by Django 4.2.1 on 2023-06-02 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0013_rename_goal_weight_goal_goal_calories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='height',
            new_name='calories_burned',
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
