# Generated by Django 4.2.1 on 2023-06-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0015_userworkout_number_of_workouts_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='calories_burned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userworkout',
            name='number_of_workouts_done',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
